// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policeman.proto

package tech.claudioed.police.man.grpc;

public interface MessageDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policies.MessageData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string threadId = 2;</code>
   */
  java.lang.String getThreadId();
  /**
   * <code>string threadId = 2;</code>
   */
  com.google.protobuf.ByteString
      getThreadIdBytes();

  /**
   * <code>string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string messageId = 4;</code>
   */
  java.lang.String getMessageId();
  /**
   * <code>string messageId = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();
}
