// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policeman.proto

package tech.claudioed.police.man.grpc;

public interface RegistryIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policies.RegistryID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
